### ISSUE TITLE
pdpipe has no attribute 'Scale'

### ISSUE THREAD

**Issue by paulandre2000** [pdpipe/pdpipe#12]
With these imports I get the following error message

![image](https://user-images.githubusercontent.com/31088235/70022935-7eb1a500-155b-11ea-96d5-586d659525f9.png)

![image](https://user-images.githubusercontent.com/31088235/70023039-dbad5b00-155b-11ea-8e9c-8e101d5619f4.png)

Is there anything else that needs to be imported?

**Comment by shaypal5** [comment]
Is it possible you went through this process?

1. Didn't have `sklearn` installed at the start.
2. Got a warning message from `pdpipe` regarding missing `sklearn` functionalities.
3. Installed `sklearn` while the kernel is up (let say, using a `!pip install scikit-learn` command in one of the notebooks cells).
4. Ran the imports again and then got just this error.

I'm asking because when `pdpipe` fails to import `sklearn` it issues a warning, avoids importing `sklearn`-dependent stages like `Scale`, and continues - since not all users might have `sklearn` installed and care about these stages.

**Comment by paulandre2000** [comment]
Sklearn was/is installed, I checked with !pip list from a cell in the notebook. When I do the 4 imports for sklearn, pandas, numpy and pdpipe, I get the warning from pdpipe that you mention ("pdpipe: Scikit-learn or skutil import failed. Scikit-learn").  When I run again the cell containing these 4 imports, I don’t get any warning,  but then I do get the same error message as I originally posted.

**Comment by paulandre2000** [comment]
Sklearn was/is installed, I checked with !pip list from a cell in the notebook. When I do the 4 imports for sklearn, pandas, numpy and pdpipe, I get the warning from pdpipe that you mention ("pdpipe: Scikit-learn or skutil import failed. Scikit-learn").  When I run again the cell containing these 4 imports, I don’t get any warning,  but then I do get the same error message as I originally posted.

**Comment by shaypal5** [comment]
Can you please uninstall `pdpipe` and then install it with the upgrade flag? As in `pip install -U pdpipe`...

Then please tell me which version of the package was installed (you can use `pip show pdpipe`).

The latest release, `v0.0.32`, should fix your issue, which was a `skutil` installation issue.

**Comment by paulandre2000** [comment]
I have done what you have described above and my issue is now resolved, I don't get any error messages. Version: 0.0.33 was installed. Thank you for your help resolving my issue!

**Comment by shaypal5** [comment]
Yay! Sure thing, friend! :)
