### ISSUE TITLE
Idea: add more linters to get more uniform codebase

### ISSUE THREAD

**Issue by marcglobality** [pdpipe/pdpipe#41]
I'm using black and isort for other projects (see e.g. https://github.com/hyperopt/hyperopt/pull/748/files) and find them quite useful to have more consistent codebase. I think you should drop python3.5 support though, as black is python3.6+. Is this something you would be open to consider?

**Comment by shaypal5** [comment]
I definitely would, as Python 3.5 end-of-life was this September, which means I'm consider dropping support for it as contributing to the community.

I've used `black` before. I just remember hating the way it refactored list and/or multi-line strings. I'm guessing this can be configured in a root-level, project wise, linter configuration file which we can add to the repository, which would be awesome.

Feel free to submit a PR moving us to this linter, but note it should include:
1. Refactoring of the code using the linter (preferably black, since it has a string auto-formatting tools and commands).
2. A linter configuration file in the root of the repository.
3. Adding a test for linting problems as a **separate** job, which will fail on any linting problem (should be trivial; if the only command in the job is the call to the CLI command of the linter, the exit code is un-erroneous if there are no linting problems, which dictates the job fail/success state).

**Comment by shaypal5** [comment]
3 is now handled (we have a flake8 lint job).

The questions regarding more opinionated linters such as black remains.
