### ISSUE TITLE
Serialization of pipelines

### ISSUE THREAD

**Issue by antopolskiy** [pdpipe/pdpipe#45]
The front page of the project says that `pdpipe` is "a simple framework for **serializable**, chainable and verbose pandas pipelines."

However, I was unable to find within the package the utilities for serialization and de-serialization of the pipelines. Is there an external tool you intended to use for serialize the pipelines or it is the missing functionality, planned for the future?

**Comment by shaypal5** [comment]
It simply means that they are built to be serializable by `pickle`, Python's built-in serialisation library. This is actually not automatic for many of the common pipeline if this issue was not taken in to consideration.

Do you think having built it methods like `save_to_disk` and `load_from_disk` that receive file paths as inputs and call `pickle` internally would make this more readily usable?

If so, please open an issue specific to that request, and we shall see if anyone is up to a PR implementing this (it's 5 minutes of coding, and couple more hours of clean testing and documentation).

**Comment by antopolskiy** [comment]
I am currently experimenting with `jsonpickle`, I think it might be a better candidate.

 The only limitation I've found so far is that you can't use lambdas as function inputs. `jsonpickle` still allows you to dump and load, but on run the pipeline will raise an error, because it cannot find `_func`.

Same applies to `pickle`, but it raises an error immediately on serialization.

**Comment by shaypal5** [comment]
`dill` can pickle lambdas, if I'm not mistakes. Take a look and think about it:
https://pypi.org/project/dill/

If you can provide a coherent solution that more readily accessible and perhaps even more powerful than just using `pickle`, I'll be delighted to include it as a contribution to this package. :)
